on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test this action
    steps:
      - name: Test action
        id: test-action
        uses: GusAntoniassi/action-setup-golangci-lint@master
        with:
          version: 1.24.0
